// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package dependable_configpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	GoCount              int32    `protobuf:"varint,1,opt,name=goCount,proto3" json:"goCount,omitempty"`
	Tps                  int32    `protobuf:"varint,2,opt,name=tps,proto3" json:"tps,omitempty"`
	MinerPrivKey         string   `protobuf:"bytes,3,opt,name=minerPrivKey,proto3" json:"minerPrivKey,omitempty"`
	AmountFromMinner     uint64   `protobuf:"varint,4,opt,name=amountFromMinner,proto3" json:"amountFromMinner,omitempty"`
	AmountPerTx          uint64   `protobuf:"varint,5,opt,name=amountPerTx,proto3" json:"amountPerTx,omitempty"`
	Ip                   string   `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,7,opt,name=port,proto3" json:"port,omitempty"`
	NewGoSpan            float32  `protobuf:"fixed32,8,opt,name=newGoSpan,proto3" json:"newGoSpan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetGoCount() int32 {
	if m != nil {
		return m.GoCount
	}
	return 0
}

func (m *Config) GetTps() int32 {
	if m != nil {
		return m.Tps
	}
	return 0
}

func (m *Config) GetMinerPrivKey() string {
	if m != nil {
		return m.MinerPrivKey
	}
	return ""
}

func (m *Config) GetAmountFromMinner() uint64 {
	if m != nil {
		return m.AmountFromMinner
	}
	return 0
}

func (m *Config) GetAmountPerTx() uint64 {
	if m != nil {
		return m.AmountPerTx
	}
	return 0
}

func (m *Config) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Config) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Config) GetNewGoSpan() float32 {
	if m != nil {
		return m.NewGoSpan
	}
	return 0
}

//func (m *Config) GetfalsifyTxFlag() float32 {
//	if m != nil {
//		return m.FalsifyTxFlag
//	}
//	return 0
//}

func init() {
	proto.RegisterType((*Config)(nil), "performance_configpb.Config")
}

func init() {
	proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4)
}

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xd0, 0xbf, 0x4a, 0x03, 0x41,
	0x10, 0x06, 0x70, 0xf6, 0x72, 0xb9, 0x98, 0x31, 0x48, 0x18, 0x2c, 0xa6, 0xb0, 0x58, 0x52, 0x1d,
	0x16, 0x36, 0x3e, 0x42, 0x40, 0x0b, 0x11, 0xc2, 0x6a, 0x2f, 0x97, 0xb0, 0x09, 0x5b, 0xec, 0xcc,
	0x30, 0xae, 0xff, 0xde, 0xd8, 0xc7, 0x90, 0xec, 0x21, 0x2a, 0x76, 0xdf, 0xf7, 0xdb, 0x1d, 0x06,
	0x06, 0x16, 0x3b, 0xe1, 0x7d, 0x3a, 0x5c, 0xa9, 0x49, 0x11, 0x3c, 0xd7, 0x68, 0x7b, 0xb1, 0x3c,
	0xf0, 0x2e, 0x3e, 0x8d, 0x2f, 0xba, 0x5d, 0x7d, 0x3a, 0xe8, 0xd6, 0xb5, 0x20, 0xc1, 0xec, 0x20,
	0x6b, 0x79, 0xe1, 0x42, 0xce, 0xbb, 0x7e, 0x1a, 0xbe, 0x2b, 0x2e, 0x61, 0x52, 0xf4, 0x99, 0x9a,
	0xaa, 0xc7, 0x88, 0x2b, 0x58, 0xe4, 0xc4, 0xd1, 0x36, 0x96, 0x5e, 0xef, 0xe2, 0x07, 0x4d, 0xbc,
	0xeb, 0xe7, 0xe1, 0x8f, 0xe1, 0x25, 0x2c, 0x87, 0x7c, 0x9c, 0xbf, 0x31, 0xc9, 0xf7, 0x89, 0x39,
	0x1a, 0xb5, 0xde, 0xf5, 0x6d, 0xf8, 0xe7, 0xe8, 0xe1, 0x74, 0xb4, 0x4d, 0xb4, 0xc7, 0x77, 0x9a,
	0xd6, 0x6f, 0xbf, 0x09, 0xcf, 0xa0, 0x49, 0x4a, 0x5d, 0xdd, 0xd3, 0x24, 0x45, 0x84, 0x56, 0xc5,
	0x0a, 0xcd, 0xaa, 0xd4, 0x8c, 0x17, 0x30, 0xe7, 0xf8, 0x76, 0x2b, 0x0f, 0x3a, 0x30, 0x9d, 0x78,
	0xd7, 0x37, 0xe1, 0x07, 0xb6, 0x5d, 0xbd, 0xc3, 0xf5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43,
	0x3f, 0x15, 0x98, 0x17, 0x01, 0x00, 0x00,
}
